packages:
  - "Frontend"
  - "packages/*"
  - "Backend"
allowBuilds:
  '@prisma/client': false
  '@prisma/engines': false
  '@tailwindcss/oxide': false
  esbuild: false
  prisma: false
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
overrides:
  '@types/react': 18.3.18
  '@types/react-dom': 18.3.7
